### ISSUE TITLE
NC's returned ballots

### ISSUE THREAD

**Issue by rootsmusic** [ElectProject/Early-Vote-2020G#172]
Today, your total for North Carolina's "[returned ballots](https://electproject.github.io/Early-Vote-2020G/NC.html)" is 246,615 but it differs from NCSBE's "[total absentee ballots cast](https://s3.amazonaws.com/dl.ncsbe.gov/Press/NC%20Absentee%20Stats%20for%202020%20General%20Election/Absentee_Stats_2020General_09272020.pdf)".

**Comment by ElectProject** [comment]
I verified they are exactly the same
