### ISSUE TITLE
[FEATURE REQUEST] Use Spontit to send daily push notification updates for the current vote count

### ISSUE THREAD

**Issue by joshwolff1** [ElectProject/Early-Vote-2020G#363]
I would love to get updated every day on the current total vote count. You should definitely check out Spontit for sending a push notification updates about the current vote count.

https://api.spontit.com/

**Comment by dalanmiller** [comment]
Why not use the Notifications API? 

https://developer.mozilla.org/en-US/docs/Web/API/notification

As well, you should probably disclose you work on Spontit.

**Comment by joshwolff1** [comment]
Sure

And Notifications API only works with browser. Not for mobile iOS devices.

**Comment by ElectProject** [comment]
I'm not implementing either. Please take this discussion elsewhere.
