### ISSUE TITLE
Washington State now reporting statewide ballot return stats

### ISSUE THREAD

**Issue by jeffbaylor** [ElectProject/Early-Vote-2020G#486]
Washington State is now reporting statewide ballot return statistics.  

If you would like help working on this project, let me know.  I am glad to help with the dev, collecting data, etc.  I could add support for the WA data, but would need access to a version of the CSV data so I can see the format and test.  

How are you getting data into the CSV file?  Are you scraping the data from the pages?  If so, I could add support for WA page.  If it is manual, I can help collect it, or write a scraper.

**Comment by ElectProject** [comment]
I appreciate the offer. I have scraper programs that collect data.

Please do not use issues to report posting of daily reports. I am very much aware of when states post. Please bear with me if I do not post immediately, as I am very busy.
