### ISSUE TITLE
Oklahoma Oct 28 afternoon update

### ISSUE THREAD

**Issue by philiptzou** [ElectProject/Early-Vote-2020G#597]
https://twitter.com/OKelections/status/1321536874889052163

Btw, I also noticed TN updated too, it's [1,962,900 now](https://sos-tn-gov-files.tnsosfiles.com/20201103EarlyAbsentee.pdf?Qqf013glLVi.qYbf3wBs0ekY9yt6iHK7).

**Comment by ElectProject** [comment]
Thanks
